server:
  port: 12945 # 修改端口
spring:
  #### 数据源
  datasource:
    #### 数据库配置
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.93.0.90:3306/jobgo_jg_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: xwEPP-Fd2zcf
    #### Hikari 连接池配置 ------ 详细配置请访问：https://github.com/brettwooldridge/HikariCP
    hikari:
      minimum-idle: 5 # 最小空闲连接数量
      idle-timeout: 180000 # 空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 10 # 连接池最大连接数，默认是10
      auto-commit: true # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      pool-name: MyHikariCP # 连接池母子
      max-lifetime: 1800000 # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 # 数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1

  #### Spring Data JPA
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  redis:
    host: 47.93.0.90
    port: 6379
    password: xwEPP-Fd2zcf
  rabbitmq:
    host: 47.93.0.90
    username: jobgo
    password: xwEPP-Fd2zcf
    virtual-host: /jobgo


fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 47.93.0.90:22122

jobgo:
  upload:
    baseUrl: http://www.wffanshao.top
  sms:
    accessKeyId: LTAI66QIUSiwS90q # accessKeyId
    accessKeySecret: nmUowBU9Uwn6VwECZjLO7JrfMOOK7F # AccessKeySecret
    signName: 易鲜良库 # 签名名称
    templateCode: SMS_171940477 # 模板名称

  filter:
    allowPaths:
      - /api/authentication
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/user/query
      -
  jwt:
    secret: jobgo@Login(Auth}*^520)&jobgo!#% # 登录校验的密钥
    pubKeyPath: /usr/local/tmp/rsa/rsa.pub # 公钥地址
    priKeyPath: /usr/local/tmp/rsa/rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: JOBGO_TOKEN
    cookieMaxAge: 30


  worker:
    workerId: 1
    datacenterId: 1

  pay:
    appId: wx8397f8696b538317
    mchId: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    httpConnectTimeoutMs: 5000
    httpReadTimeoutMs: 10000
    notifyUrl: http://test/notify


